### ISSUE TITLE
Key management missing

### ISSUE THREAD

**Issue by dmp1ce** [rethab/h-gpgme#13]
I couldn't find any functions for key management such as creating a key or deleting a key.

Is there a plan to add key management functions to this project?

**Comment by rethab** [comment]
There is not. You are very free to to contribute :)

- Reto

**Comment by dmp1ce** [comment]
I'm working on it but I ran into a "Not implemented" error which I'm not sure what to do with. I've documented the error in my fork here: https://github.com/dmp1ce/h-gpgme/issues/1

**Comment by rethab** [comment]
@dmp1ce I understand you have found a solution to your issue? Let me know if not, and I'll take a look at it!

\- Reto

**Comment by dmp1ce** [comment]
Yeah. I'm making progress. Right now I'm trying to figure out how to structure the key generation parameters.

**Comment by dmp1ce** [comment]
@rethab Do you think I am on a good path so far with the parameters for gen key? https://github.com/dmp1ce/h-gpgme/blob/genKey/test/KeyTest.hs#L88
https://github.com/dmp1ce/h-gpgme/blob/genKey/src/Crypto/Gpgme/Types.hs#L161

I have created optional parameters for Key-Type and Key-Length. The rest of the parameters can be provided using a ByteString.

**Comment by rethab** [comment]
I would be very reluctant to accepting a string as a parameter with random arguments. In my opinion, this defeats a number of arguments that speak for using a language like haskell in the first place (eg. safty with regard to what you can pass in and what is valid input, being able to guess what could be passed in based on the type of the arguments, ..).

Also, if you once accept any parameter via text, it will basically be impossible to change that in the future, because people will never get a compile error if we move a certain parameter from the 'string-parameters' to the 'typed-parameters'.

**Comment by dmp1ce** [comment]
I completed the `genKey` function which creates a key based on the passed in parameters. I tried to add typed parameters where I could. Some of the parameters I didn't know what the options could be, so I just used `ByteString`.

I'll work on functions for deleting and then listing keys next.

Can you look at my `genKey` branch and let me know if it is something that could get merged or if you notice anything that should change before merging? Would you like me to go ahead and do a pull request? I have some tests commented out because they take to long during development and they prompt me.

https://github.com/dmp1ce/h-gpgme/tree/genKey

**Comment by rethab** [comment]
Hi @dmp1ce, thanks for working on this! Please go ahead and open a pull request -- hopefully I find some time to look at it over the weekend.

- Reto
